# Generated by Django 3.0.5 on 2020-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsociety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='maxppt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crops',
            name='maxtemp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crops',
            name='minppt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crops',
            name='mintemp',
            field=models.IntegerField(),
        ),
    ]
